GUI seems finished

diff --git a/tvtcommands/vm-create b/tvtcommands/vm-create
--- a/tvtcommands/vm-create
+++ b/tvtcommands/vm-create
@@ -10,6 +10,7 @@ run_now=false
 distro="debian"
 
 while [[ $# -gt 0 ]]; do
+    echo "$1"
     case "$1" in
     --xfce|-x)
         xfce=true
@@ -19,6 +20,11 @@ while [[ $# -gt 0 ]]; do
         ;;
     --distro|-d)
         distro="$2"
+        if [[ -z "$distro" ]]; then
+            echo "Error: --distro|-d requires a value."
+            echo "Try 'vm-create --help' for usage."
+            exit 1
+        fi
         shift
         ;;
     --isolated|-i)
@@ -50,6 +56,11 @@ while [[ $# -gt 0 ]]; do
         echo "--help, -h              Show this help message and exit."
         echo ""
         exit 0
+        ;;
+    -*)
+        echo "Error: Unknown option '$1'."
+        echo "Try 'vm-create --help' for usage."
+        exit 1
         ;;
     *)
         name="$1"
diff --git a/tvtcommands/vn-create b/tvtcommands/vn-create
--- a/tvtcommands/vn-create
+++ b/tvtcommands/vn-create
@@ -34,6 +34,11 @@ while [[ $# -gt 0 ]]; do
         echo "--help, -h          Show this help message and exit."
         echo ""
         ;;
+    -*)
+        echo "Error: Unknown option '$1'."
+        echo "Try 'vm-create --help' for usage."
+        exit 1
+        ;;
     *)
         name="$1"
         ;;
@@ -52,10 +57,9 @@ $disable_dns && args+=(--disable-dns)
 [[ -n "$gateway" ]] && args+=(--gateway "$gateway")
 $internal && args+=(--internal)
 [[ -n "$subnet" ]] && args+=(--subnet "$subnet")
-
-if podman network create "${args[@]}" "$name"; then
+if output=$(podman network create "${args[@]}" "$name" 2>&1); then
     echo "Network $name created."
 else
-    echo "Network creation failed."
+    echo "Network creation failed. Details : $output"
     exit 1
 fi
diff --git a/tvtcommands/vn-info b/tvtcommands/vn-info
--- a/tvtcommands/vn-info
+++ b/tvtcommands/vn-info
@@ -1,4 +1,23 @@
 #!/bin/bash
 
 name="$1"
-podman network inspect "$name"
+if [[ -z "$name" ]]; then
+    echo "Error: A name is required."
+    echo "Try 'vm-info --help' for usage."
+    exit 1
+elif [[ $name == "-h" || $name == "--help" ]]; then
+    echo "Usage: vn-info NAME"
+    echo "Display information about an existing Podman network."
+    echo ""
+    echo "Options:"
+    echo "--help, -h          Show this help message and exit."
+    echo ""
+    exit 0
+fi
+echo "Name : $(podman network inspect --format "{{.Name}}" "$name")"
+echo "Driver : $(podman network inspect --format "{{.Driver}}" "$name")"
+echo "Internal : $(podman network inspect --format "{{.Internal}}" "$name")"
+echo "Created : $(podman network inspect --format "{{.Created}}" "$name")"
+echo "DNS : $(podman network inspect --format "{{.DNSEnabled}}" "$name")"
+echo "Subnet : $(podman network inspect --format "{{range .Subnets}}{{.Subnet}}{{end}}" "$name")"
+echo "Gateway : $(podman network inspect --format "{{range .Subnets}}{{.Gateway}}{{end}}" "$name")"
